on:
    push:
        tags: '*'

jobs:
    release:
        name: Build & release
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - uses: actions/setup-go@v4
              with:
                go-version: '>=1.18'
                cache: true

            - name: Install dependencies
              if: runner.os == 'Linux'
              run: |
                sudo apt-get update
                sudo apt-get install libasound2-dev libgl1-mesa-dev xorg-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
            
            - name: Build
              run: bash ./build.sh

            - name: Calculate executable name
              run:
                if [[ ${{runner.os}} == "Windows" ]]; then
                    EXECUTABLE_NAME="bamboo.exe"
                else
                    EXECUTABLE_NAME="bamboo"
                fi
                echo "EXECUTABLE_NAME=$EXECUTABLE_NAME" >> $GITHUB_ENV
                echo Executable name is $EXECUTABLE_NAME

            - name: Package everything into an archive
              run: tar -cvf Bamboo-${{ runner.os }}.tar.gz $EXECUTABLE_NAME assets

            - name: Generate release description
              run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"

            - name: Publish release
              uses: softprops/action-gh-release@v1
              with:
                body_path: ".github/RELEASE-TEMPLATE.md"
                files: Bamboo-${{runner.os}}.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}