on:
    push:
        tags: '*'

jobs:
    release:
        name: Build & release
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                arch: [amd64, arm64]
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - uses: actions/setup-go@v4
              with:
                go-version: '>=1.18'
                cache: true

            - name: Echo os
              run:
                echo ${{ matrix.arch }}

            - name: Install dependencies
              if: runner.os == 'Linux'
              run: |
                sudo apt-get update
                sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

            - name: Xvfb
              if: runner.os == 'Linux'
              run: |
                Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            
            - name: Build
              run: bash ./build.sh ${{ matrix.arch }}
            
            - name: Generate release description
              run: bash ./generate-release-description.sh

            - name: Release!
              uses: softprops/action-gh-release@v1
              with:
                body_path: ".github/RELEASE-TEMPLATE.md"
                files: ${{github.repository}}-${{matrix.arch}}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}